version: '2'
services:
    tm:
        image: tomcat
        environment:
            TZ: Asia/Shanghai
        volumes:
            - ./webapps:/usr/local/tomcat/webapps/
            - ./conf:/usr/local/tomcat/conf/
            - ./bin/catalina.sh:/usr/local/tomcat/bin/catalina.sh 
            - ./logs:/usr/local/tomcat/logs/
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "29091:8080/tcp"
