version: '2'
services:
  mysql57:
    image: mysql:5.7.28
    volumes:
      - ./logs:/logs
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
