version: '2'
services:
  mysql57:
    image: mysql:5.7.28
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/logs
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
