# https://hub.docker.com/_/mongo
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
            - ./data:/data/db
    ports:
            - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: chada123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27020:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: chada123

