# https://hub.docker.com/_/mysql?tab=description
version: '3.1'

services:

  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/logs
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 3318:8080
      

