version: '2'
services:
        portainer:
                image: portainer/portainer
                ports:
                        - "9001:9000"
                volumes:
                        - ./data:/data
                        - /var/run/docker.sock:/var/run/docker.sock
                restart: always
