version: '2'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper

  # kafka version: 1.1.0
  # scala version: 2.12
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.103
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.103:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "jjh"
    depends_on:
      - zoo1
    container_name: kafka

  kafka-manager1:
    image: sheepkiller/kafka-manager
    ports:
      - "9005:9000"
    environment:
      ZK_HOSTS: "zoo1:2181"
    depends_on:
      - kafka1
    container_name: kafka-manager
