## https://cloud.tencent.com/developer/article/1352195
redis:
        image: redis
        container_name: my_redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
                - ./data:/data
                - ./redis.conf:/usr/local/etc/redis/redis.conf
        ports:
                - "10001:6379"
        restart: always

